{
 "title": "L2 Tests",
 "time": { "from": "2026-03-26T12:30:01.440Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "jobname",
    "label": "Job Name",
    "query": {
     "query": "label_values(chain_head_block_number,job)"
    }
   },
   {
    "name": "window",
    "query": "1s,2s,5s,10s,15s,20s,30s,60s,2m,4m,5m,10m,20m,30m"
   }
  ]
 },
 "panels": [
  {
   "title": "Block production",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/block.gauge\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r.node }))\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Creates/Deletes - sequencer",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.arkiv_store/creates.count\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Creation Rate\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.arkiv_store/deletes.count\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Deletion Rate\" }))  "
    }
   ]
  },
  {
   "title": "Batcher pending bytes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"op_batcher_default_pending_da_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Celestia balance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_celestia_account_balance\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Creates/Deletes bytes - sequencer",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.arkiv_store/creates_bytes.count\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Creation Rate\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.arkiv_store/deletes_bytes.count\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Deletion Rate\" }))  "
    }
   ]
  },
  {
   "title": "Change in db size",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_sqlite_db_size_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Sqlite\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_geth_db_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Geth change\" }))\r\n"
    }
   ]
  },
  {
   "title": "Sequencer sizes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_sqlite_db_size_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Sqlite\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_geth_db_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Geth\" }))\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_sqlite_wal_size_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"db-wal\" }))\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_da_data_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"da-data\" }))\r\n"
    }
   ]
  },
  {
   "title": "Sequencer-pebble db",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_pebble_db_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"db-wal\" }))\r\n"
    }
   ]
  },
  {
   "title": "Validator sizes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_sqlite_db_size_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Sqlite\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_geth_db_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Geth\" }))\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_sqlite_wal_size_bytes\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"db-wal\" }))\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_da_data_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"da-data\" }))\r\n"
    }
   ]
  },
  {
   "title": "Gas used in block",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/gas_used.gauge\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: mean, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Sqlite\" }))\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/gas_used.gauge\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: mean, createEmpty: false)\r\n  // Unit: 1s calculates the change per second\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Geth\" }))\r\n"
    }
   ]
  },
  {
   "title": "Mean gas in block",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/gas_used_hist.histogram\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"sequencer\")\r\n  |> aggregateWindow(every: ${window}, fn: mean, createEmpty: false)\r\n \r\n\r\n"
    },
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"geth.chain/head/gas_used_hist.histogram\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n  |> filter(fn: (r) => r[\"node\"] == \"validator\")\r\n  |> aggregateWindow(every: ${window}, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "DA production per seconds",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_da_data_size\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Calculate the rate of change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _field: \"da-data-rate\" }))"
    }
   ]
  },
  {
   "title": "Last scanned L1 block",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_l1_last_scanned_block\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ _value: r._value*1.0, _time: r._time, _field: \"L1 Block Head\" }))\r\n"
    }
   ]
  },
  {
   "title": "Mainnet gas price",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_mainnet_gas_price\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ _value: r._value*0.000000001, _time: r._time, _field: \"Mainnet gas price (GWEI)\" }))\r\n"
    }
   ]
  },
  {
   "title": "L1 transactions count",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_l1_transactions_total\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ _value: r._value*1.0, _time: r._time, _field: \"Total L1 transactions\" }))\r\n"
    }
   ]
  },
  {
   "title": "L1 Gas usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_l1_gas_used_total\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Calculate the rate of change per second\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _field: \"da-data-rate\" }))"
    }
   ]
  },
  {
   "title": "Mainnet gas price",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_mainnet_gas_price\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  // Calculate the rate of change per second\r\n  |> map(fn: (r) => ({ r with _field: \"mainnet-gas-price\" }))"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"arkiv-tests\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arkiv_free_space\")\r\n  |> filter(fn: (r) => r[\"test\"] == \"${jobname}\")\r\n  |> aggregateWindow(every: ${window}, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ _value: r._value*0.000000001, _time: r._time, _field: \"Free space\" }))\r\n"
    }
   ]
  }
 ]
}