name: Arkiv System Pure Reth Test

on:
  workflow_dispatch:
    inputs:
      timeout-minutes:
        description: "Timeout for jobs"
        required: true
        default: "7000"
      worker:
        description: "Workers"
        required: false
        default: "bare-metal"
      arkiv-reth:
        description: "Arkiv pure reth version used for tests"
        required: true
        default: "v0.1.0-pure-2"
      test-length:
        description: "Test length in seconds"
        required: true
        default: "36000"
      block-every:
        description: "Block time in seconds"
        required: true
        default: "2"
      block-limit:
        description: "Block gas limit"
        required: true
        default: "30000000"
      test-scenario:
        description: "Test scenario to run"
        required: true
        default: "LocustWriteOnly"
      run-locust:
        description: "Whether to run locust stress test"
        required: true
        default: "false"
      test-users:
        description: "Number of users to run"
        required: true
        default: "10"
      dc-write-only-payload-size:
        description: "Payload size for dc write only test"
        required: true
        default: "3000"
      arkiv-sdk-js:
        description: "Arkiv SDK Tag/commit used for tests"
        required: true
        default: "atlas"
      is-external:
        description: "Whether test already deployed network"
        required: true
        default: "false"
      external-rpc-url:
        description: "RPC URL of external network, if is-external is true"
        required: false
        default: "https://v2test.hoodi.arkiv.network/rpc"

permissions:
  contents: read

jobs:
  arkiv-system-testing:
    name: Test Arkiv System Pure Reth
    timeout-minutes: ${{ fromJSON(inputs.timeout-minutes) }}
    runs-on: ${{ inputs.worker }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup after previous runs
        if: ${{ inputs.is-external == 'false' }}
        run: |
          rm -rf sequencer-data genesis.json *.pid *.log

      - name: Set test name
        id: test-name
        run: |
          WORKER_NAME=$(hostname)
          python notify-test-start.py \
            --parameters \
              testLength=${{ fromJSON(inputs.test-length) }} \
              runsOn=$WORKER_NAME \
              blockEvery=${{ inputs.block-every }} \
              rethVersion=${{ inputs.arkiv-reth }} \
              blockLimit=${{ inputs.block-limit }} \
              dcWriteOnlyPayloadSize=${{ inputs.dc-write-only-payload-size }} \
              testScenario=${{ inputs.test-scenario }} \
              testUsers=${{ inputs.test-users }} \
              isExternal=${{ inputs.is-external }} \
              githubRunId=${{ github.run_id }} \
              gitref=${{ github.ref }} \
              arkiv-sdk-js=${{ inputs.arkiv-sdk-js }}

          TEST_NAME=$(cat test-name.txt)
          echo "val=$TEST_NAME" >> $GITHUB_OUTPUT
          echo "worker=$WORKER_NAME" >> $GITHUB_OUTPUT
          if [ "${{ inputs.test-scenario }}" = "LocustWriteOnly" ]; then
            echo "scenario=LocustWriteOnly" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.test-scenario }}" = "Empty" ]; then
            echo "scenario=empty" >> $GITHUB_OUTPUT
          else
            echo "Error: Unknown test scenario ${{ inputs.test-scenario }}"
            exit 1
          fi
          echo "$TEST_NAME"
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}

      - name: Register binary folders in PATH
        run: |
          mkdir "${{ github.workspace }}/bin"
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

          mkdir -p $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Get Arkiv pure reth binary
        if: ${{ inputs.is-external == 'false' }}
        run: |
          set -euxo pipefail
          BIN_PATH=${{ github.workspace }}/bin
          ARKIV_RETH_TAG=${{ inputs.arkiv-reth }}

          ARKIV_RETH_XZ_URL="https://github.com/arkiv-network/arkiv-op-reth/releases/download/${ARKIV_RETH_TAG}/arkiv-op-reth-${ARKIV_RETH_TAG}-linux-amd64.tar.xz"
          ARKIV_RETH_TGZ_URL="https://github.com/arkiv-network/arkiv-op-reth/releases/download/${ARKIV_RETH_TAG}/arkiv-op-reth-${ARKIV_RETH_TAG}-integration-tests.tar.gz"
          TMP_XZ="arkiv-reth.tar.xz"
          TMP_TGZ="arkiv-reth.tar.gz"

          if curl -fSL -o "$TMP_XZ" "$ARKIV_RETH_XZ_URL"; then
            tar -xJf "$TMP_XZ"
          else
            echo ".tar.xz not available, trying integration-tests tar.gz"
            curl -fSL -o "$TMP_TGZ" "$ARKIV_RETH_TGZ_URL"
            tar -xzf "$TMP_TGZ"
            rm -f "$TMP_TGZ"
          fi
          rm -f "$TMP_XZ"

          mv arkiv-node "$BIN_PATH/arkiv-node"
          mv arkiv-cli "$BIN_PATH/arkiv-cli"

          arkiv-node --version
          arkiv-cli --version

      - name: Download arkiv-sdk-js and build package
        run: |
          git clone https://github.com/Arkiv-Network/arkiv-sdk-js
          (
            cd arkiv-sdk-js
            git checkout ${{ inputs.arkiv-sdk-js }}
            bun install
            bun run package:test
            ls -lha arkiv-network-sdk-latest.tgz
          )

          (cd arkiv-sdk-js/test && bun install)
          bun install

      - name: Setup python dependencies
        id: poetry
        run: |
          poetry install
          VENV_PATH=$(poetry env info --path)
          VENV_PYTHON="$VENV_PATH/bin/python"
          echo "python=$VENV_PYTHON" >> $GITHUB_OUTPUT

      - name: Setup pure reth genesis
        if: ${{ inputs.is-external == 'false' }}
        run: |
          set -euxo pipefail

          PURE_RETH_CHAIN_ID=42069 \
          PURE_RETH_BLOCK_TIME_SECONDS=${{ inputs.block-every }} \
          PURE_RETH_GAS_LIMIT=${{ inputs.block-limit }} \
          $PYTHON_BIN generate-pure-reth-genesis.py

          arkiv-cli inject-predeploy genesis.json
          arkiv-node init --datadir ./sequencer-data --chain genesis.json > init_genesis.log 2>&1

          TEST_NAME=${{ steps.test-name.outputs.val }}
          curl -sS -X POST -F "file=@genesis.json" ${TRACKER_BACKEND_URL}/test/${TEST_NAME}/upload/file
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}
          PYTHON_BIN: ${{ steps.poetry.outputs.python }}

      - name: Start pure reth node
        if: ${{ inputs.is-external == 'false' }}
        run: |
          set -euxo pipefail

          arkiv-node node \
            --dev \
            --dev.block-time=${{ inputs.block-every }}s \
            --dev.mnemonic="$DEV_MNEMONIC" \
            --chain=genesis.json \
            --datadir=./sequencer-data \
            --http \
            --http.port=18645 \
            --http.addr=0.0.0.0 \
            --http.api="admin,debug,eth,txpool,net,web3,rpc,reth,miner" \
            --ws \
            --ws.addr=127.0.0.1 \
            --ws.api="admin,debug,eth,txpool,net,web3,rpc,reth,miner" \
            --ws.origins="*" \
            --ws.port=8646 \
            --disable-auth-server \
            --disable-discovery \
            --no-persist-peers \
            --builder.gaslimit=${{ inputs.block-limit }} \
            --metrics 127.0.0.1:6160 \
            > arkiv-node.log 2>&1 & echo $! > arkiv-node.pid

          python -u wait-for-blocks.py \
            --l2-url http://localhost:18645 \
            --l1-url "" \
            --timeout 60 \
            --blocks 3
        env:
          DEV_MNEMONIC: "parent picture garment parrot churn record stadium pill rocket craft fish fiscal clip virus view diary replace wealth extra kitten door enforce piece nut"

      - name: Run js-sdk library tests
        if: false
        continue-on-error: true
        run: |
          (cd arkiv-sdk-js/test && bun run test:component)
        env:
          ARKIV_SDK_TEST_RPC_URL: http://localhost:18645
          ARKIV_SDK_TEST_WS_URL: ws://localhost:8646
          ARKIV_SDK_TEST_CHAIN_ID: 42069
          ARKIV_SDK_TEST_CRUD_TIMEOUT: 30000
          PRIVATE_KEY: "0x010042e63deaeb32f323f62126bf68fce47a5c64d3685969ca7803fc337879b9"

      - name: Gather metrics
        if: ${{ inputs.is-external == 'false' }}
        run: |
          export JOB_NAME=${{ steps.test-name.outputs.val }}
          WORKER_NAME=${{ steps.test-name.outputs.worker }}
          export INSTANCE_NAME=$WORKER_NAME
          python -u gather-metrics.py > gather-metrics.log 2>&1 & echo $! > gather-metrics.pid
        env:
          INFLUXDB_URL: ${{ secrets.INFLUXDB_URL }}
          INFLUXDB_TOKEN: my-super-secret-auth-token
          INFLUXDB_ORG: arkiv-network
          INFLUXDB_BUCKET: arkiv-tests
          METRICS_SCRAPE_TARGETS: ""

      - name: Scrape reth metrics to InfluxDB
        if: ${{ inputs.is-external == 'false' }}
        run: |
          export JOB_NAME=${{ steps.test-name.outputs.val }}
          WORKER_NAME=${{ steps.test-name.outputs.worker }}
          export INSTANCE_NAME=$WORKER_NAME
          python -u scrape-reth-metrics.py > scrape-reth-metrics.log 2>&1 & echo $! > scrape-reth-metrics.pid
        env:
          INFLUXDB_URL: ${{ secrets.INFLUXDB_URL }}
          INFLUXDB_TOKEN: my-super-secret-auth-token
          INFLUXDB_ORG: arkiv-network
          INFLUXDB_BUCKET: arkiv-tests
          RETH_SCRAPE_INTERVAL_SECONDS: "5"
          RETH_SEQUENCER_METRICS_URL: http://127.0.0.1:6160/debug/metrics/prometheus
          RETH_VALIDATOR_METRICS_URL: ""

      - name: Notify that the test is starting
        run: |
          TEST_NAME=${{ steps.test-name.outputs.val }}
          curl -sS -X POST ${TRACKER_BACKEND_URL}/test/start -H "Content-Type: application/json" -d '{"name":"'"$TEST_NAME"'"}'
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}

      - name: Show balances of main accounts
        run: |
          poetry run python show-account-values.py --rpc-url ${{ inputs.is-external == 'true' && inputs.external-rpc-url || 'http://localhost:18645' }} --save-to-compare account-values.json
        env:
          MNEMONIC: "parent picture garment parrot churn record stadium pill rocket craft fish fiscal clip virus view diary replace wealth extra kitten door enforce piece nut"

      - name: Simple entity test
        if: ${{ inputs.is-external == 'false' }}
        run: |
          bun src/create_entity.ts
        env:
          RPC_URL: http://localhost:18645
          CHAIN_ID: "42069"
          PRIVATE_KEY: "0x010042e63deaeb32f323f62126bf68fce47a5c64d3685969ca7803fc337879b9"

      - name: Start snapshot loop
        run: |
          (
            INTERVAL=60
            START_TIME=$(date +%s)
            TARGET_TIME=$START_TIME
            ITERATION_NUMBER=1

            while true; do
              TARGET_TIME=$(( TARGET_TIME + INTERVAL ))
              CURRENT_TIME=$(date +%s)
              SLEEP_TIME=$(( TARGET_TIME - CURRENT_TIME ))

              if [ "$SLEEP_TIME" -gt 0 ]; then
                sleep "$SLEEP_TIME"
              fi

              RELATIVE_TIME=$(( ITERATION_NUMBER * INTERVAL ))

              $PYTHON_BIN query-arkiv.py --test_name ${{ steps.test-name.outputs.val }} --save "results-$RELATIVE_TIME.json" >> query-arkiv-loop.log 2>&1 || true
              $PYTHON_BIN show-account-values.py --rpc-url ${{ inputs.is-external == 'true' && inputs.external-rpc-url || 'http://localhost:18645' }} --save "results-$RELATIVE_TIME.json" --compare account-values.json >> show-accounts-arkiv-loop.log 2>&1 || true
              TEST_NAME=${{ steps.test-name.outputs.val }}
              $PYTHON_BIN push-results.py --test-name $TEST_NAME --file "results-$RELATIVE_TIME.json" --seconds $RELATIVE_TIME >> push-results-loop.log 2>&1 || true

              ITERATION_NUMBER=$(( ITERATION_NUMBER + 1 ))
            done
          ) >> snapshot-loop.log 2>&1 &
        env:
          MNEMONIC: "parent picture garment parrot churn record stadium pill rocket craft fish fiscal clip virus view diary replace wealth extra kitten door enforce piece nut"
          INFLUXDB_URL: ${{ secrets.INFLUXDB_URL }}
          INFLUXDB_TOKEN: my-super-secret-auth-token
          INFLUXDB_ORG: arkiv-network
          INFLUXDB_BUCKET: arkiv-tests
          IS_EXTERNAL: ${{ inputs.is-external }}
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}
          PYTHON_BIN: ${{ steps.poetry.outputs.python }}

      - name: Wait indefinitely
        if: ${{ steps.test-name.outputs.scenario == 'LocustWriteOnly' && inputs.run-locust == 'false' }}
        run: |
          sleep infinity

      - name: Start locust write only test
        if: ${{ steps.test-name.outputs.scenario == 'LocustWriteOnly' && inputs.run-locust == 'true' }}
        run: |
          if [ "${{ inputs.is-external }}" = "true" ]; then
            export LOCUST_HOST=${{ inputs.external-rpc-url }}
          else
            export LOCUST_HOST=http://localhost:18645
          fi
          set -x
          LOCUST_TEST_NAME=dc_write_only
          poetry run locust -f stress/l3/$LOCUST_TEST_NAME.py \
            --csv=$LOCUST_TEST_NAME \
            --headless \
            -u=${{ inputs.test-users }} \
            -r=100 \
            -t=${{ inputs.test-length }} \
            --print-stats \
            --html "locust.html" > locust.log 2>&1 || true
        env:
          CHAIN_ID: "42069"
          DC_WRITE_ONLY_PAYLOAD_SIZE: ${{ inputs.dc-write-only-payload-size }}
          MNEMONIC: "parent picture garment parrot churn record stadium pill rocket craft fish fiscal clip virus view diary replace wealth extra kitten door enforce piece nut"

      - name: Stop services
        if: ${{ inputs.is-external == 'false' }}
        run: |
          for pid_file in scrape-reth-metrics.pid gather-metrics.pid arkiv-node.pid; do
            if [ -f "$pid_file" ]; then
              kill "$(cat "$pid_file")" || true
            fi
          done

      - name: Cleanup metrics gateway
        if: ${{ inputs.is-external == 'false' }}
        run: |
          WORKER_NAME=${{ steps.test-name.outputs.worker }}
          curl -sS -X DELETE https://l2.arkiv-global.net/eKUSzE1KvC/metrics/job/${{ steps.test-name.outputs.val }}/instance/$WORKER_NAME

      - name: Notify test server about test finish
        if: always()
        run: |
          TEST_NAME=${{ steps.test-name.outputs.val }}
          curl -sS -X POST ${TRACKER_BACKEND_URL}/test/finish -H "Content-Type: application/json" -d '{"name":"'"$TEST_NAME"'"}'
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}

      - name: Upload test report
        if: always()
        run: |
          TEST_NAME=${{ steps.test-name.outputs.val }}
          if [ -f locust.html ]; then
            curl -sS -X POST -F "file=@locust.html" ${TRACKER_BACKEND_URL}/test/${TEST_NAME}/upload/file
          fi
          if [ -f locust.log ]; then
            curl -sS -X POST -F "file=@locust.log" ${TRACKER_BACKEND_URL}/test/${TEST_NAME}/upload/file
          fi
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}

      - name: Compress Arkiv logs
        if: always()
        run: |
          tar -czf arkiv-logs.tar.gz *.log *.json || true

      - name: Upload logs
        if: always()
        run: |
          TEST_NAME=${{ steps.test-name.outputs.val }}
          if [ -f arkiv-logs.tar.gz ]; then
            curl -sS -X POST -F "file=@arkiv-logs.tar.gz" ${TRACKER_BACKEND_URL}/test/${TEST_NAME}/upload/file
          fi
        env:
          TRACKER_BACKEND_URL: ${{ secrets.TRACKER_BACKEND_URL }}
